### ISSUE TITLE
Docs: Badge fills screen on smaller devices

### ISSUE THREAD

**Issue by myuwono** [Covata/delta-sdk-python#41]
rst needs to be altered as follows:
```rst
.. |Build Status|
    image:: ...
    :target: ...
    :class: badge
```
with the following css:
```css
img.badge {
    width: auto;
}
```
